### ISSUE TITLE
可以release pdf吗

### ISSUE THREAD

**Issue by standback** [xiaoweiChen/Cpp-Templates-2nd#7]
感谢你的整理。

建议可以定时的release pdf. 
因为对大家来说。如果 要阅读，还要去配置 latex环境 有点麻烦。

我也不是太了解latex. 好像他可以直接 输出 pdf.
是不是可以直接 release pdf.方便大家取用。

thanks.

**Comment by xiaoweiChen** [comment]
在Release页面有的，可以自行下载
https://github.com/xiaoweiChen/Cpp-Templates-2nd/releases/tag/20220903

**Comment by xiaoweiChen** [comment]
我好奇一下，为什么想要定期更新这本书呢？
我个人认为，这本书是2017年出版的了，到现在也5年多了，内容也基本上固定了，所以自己觉得一次性弄完的比较好。
